spring.application.name=nebula-rest-api
app.version=@project.version@
server.port=8445
cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:https://milkyway.test,https://*.milkyway.test,https://milkyway.inet,https://*.milkyway.inet,https://*.milkyway,https://*.test.milkyway,https://*.dev.milkyway}

spring.threads.virtual.enabled=true

app.jwt.secret=${APP_JWT_SECRET}

header.for.auth.serv=${HEADER_FOR_AUTH_SERVER}
app.resources.base-url=${APP_RESOURCES_BASE_URL:https://milkyway.test/resources/nebula/}
auth.serv.api.v1.url=${ANDROMEDA_AUTH_SERV_TEST_URL}/api/v1/

auth.serv.api.v1.url.account=${auth.serv.api.v1.url}public/account
auth.serv.api.v1.url.account.register=${auth.serv.api.v1.url}public/account/register
auth.serv.api.v1.url.account.confirm=${auth.serv.api.v1.url}public/account/confirm
auth.serv.api.v1.url.account.unlock=${auth.serv.api.v1.url}public/account/unlock
auth.serv.api.v1.url.account.reset=${auth.serv.api.v1.url}public/account/reset-password
auth.serv.api.v1.url.account.changepass=${auth.serv.api.v1.url}account/change-password
auth.serv.api.v1.url.account.token=${auth.serv.api.v1.url}auth/login
auth.serv.api.v1.url.access.refresh=${auth.serv.api.v1.url}auth/refresh-access

image.avatar.path=${IMAGE_AVATAR_PATH:/app/fileserver/nebula/avatars}

# JPA/Hibernate - base configuration
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

#Swagger/OpenAPI configuration
springdoc.swagger-ui.path=/nebula/swagger-ui.html
springdoc.swagger-ui.config-url=/nebula/v3/api-docs/swagger-config
springdoc.api-docs.path=/nebula/v3/api-docs
springdoc.swagger-ui.url=/nebula/v3/api-docs

# DataSource - connection configuration
spring.datasource.url=${NEBULA_TEST_DB_URL}
spring.datasource.username=${NEBULA_TEST_USERNAME}
spring.datasource.password=${NEBULA_TEST_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# HikariCP - pool configuration
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=5000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=None

management.endpoints.web.base-path=/api/actuator
management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.endpoint.prometheus.access=unrestricted
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
