PATCH https://localhost:8081/api/v1/users/profile
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIyZWM5ZWRjZS1lZTFlLTRmMzQtYmNkZi1iYmFmN2NiN2JiNGYiLCJzdWIiOiIxMjM0NTY4MDciLCJpc3MiOiJBbmRyb21lZGFBdXRoQXBpIiwicm9sZXMiOlt7ImlkIjoxLCJuYW1lIjoiUk9MRV9VU0VSIn1dLCJ2ZXJzaW9uIjo2LCJyZXZva2VkIjpmYWxzZSwiaWF0IjoxNzc4MTcwNzk1LCJleHAiOjE3NzgxNzEwOTV9.C8g_frd24yRc-YCfgphtOUDfUF8YbFSIQr7Oi-mJor7lBtqVoPRy-ddoEE5_D7sn3Jj0ojV1Xl7k_G3SOe-clg
# used to update user profile data stoerd in nebula database,
# requires header: Content-Type: application/json
# Examples
# PATCH https://nebula.test.milkyway/api/v1/users/profile
# PATCH http://localhost:8081/api/v1/users/profile

{
  "userId": 15,
  "firstName": "Ralf",
  "lastName": "Blue",
  "birthdate": "1986-01-26T11:10:25.723Z",
  "nationalityId": 100,
  "genderId": 2
}
